// ─────────────────────────────────────────────────────────────────────────────
// gen-test-key.ts — compile the progress-test answer key.
//
// Walks the Python Basics content and emits functions/lib/progressTestKey.generated.ts
// — a compact map of every progress-test lesson's correct answers, used by the
// server to grade submissions authoritatively (see functions/lib/gradeProgressTest.ts).
//
// Run:  npx tsx gen-test-key.ts
// CI regenerates this and fails if the committed file drifts from the content.
// ─────────────────────────────────────────────────────────────────────────────

import { writeFileSync } from 'node:fs'
import { chapters, lessonKey } from './src/data/basics/index'
import type { ProgressTestQuestion } from './src/types/basics'
import type { LessonKey, ProgressTestKey, QuestionSpec } from './functions/lib/gradeProgressTest'

function specOf(q: ProgressTestQuestion): QuestionSpec {
  switch (q.qType) {
    case 'mcq':
      return { t: 'mcq', c: q.correctOptionId }
    case 'predict-output':
      return { t: 'po', e: q.expectedOutput }
    case 'fill-in-blank':
      return { t: 'fib', a: q.acceptedAnswers }
  }
}

const key: ProgressTestKey = {}

for (const chapter of chapters) {
  for (const mod of chapter.modules) {
    for (const lesson of mod.lessons) {
      if (lesson.type !== 'progress-test') continue

      const id = lessonKey(chapter.slug, mod.slug, lesson.slug)
      const banks = lesson.questionBanks.map((bank) => {
        const rec: Record<string, QuestionSpec> = {}
        for (const q of bank) rec[q.id] = specOf(q)
        return rec
      })
      const available = lesson.questionBanks.reduce((n, b) => n + b.length, 0)
      const entry: LessonKey = {
        drawCount: Math.min(lesson.presentCount, available),
        banks,
      }
      key[id] = entry
    }
  }
}

// Stable, sorted output so the committed file diffs cleanly.
const sorted: ProgressTestKey = {}
for (const id of Object.keys(key).sort()) sorted[id] = key[id]

const banner =
  '// AUTO-GENERATED by gen-test-key.ts — do not edit by hand.\n' +
  '// Run `npx tsx gen-test-key.ts` to regenerate. CI fails if this drifts.\n'
const body =
  "import type { ProgressTestKey } from './gradeProgressTest'\n\n" +
  'export const PROGRESS_TEST_KEY: ProgressTestKey = ' +
  JSON.stringify(sorted, null, 2) +
  '\n'

writeFileSync('functions/lib/progressTestKey.generated.ts', banner + body)
console.log(
  `Wrote functions/lib/progressTestKey.generated.ts — ${Object.keys(sorted).length} progress-test lessons.`,
)
