// AUTO-GENERATED by gen-test-key.ts — do not edit by hand.
// Run `npx tsx gen-test-key.ts` to regenerate. CI fails if this drifts.
import type { ProgressTestKey } from './gradeProgressTest'

export const PROGRESS_TEST_KEY: ProgressTestKey = {
  "completing-basics.final-test.test": {
    "drawCount": 15,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "6.0"
        },
        "q3": {
          "t": "po",
          "e": "4"
        },
        "q4": {
          "t": "po",
          "e": "5"
        },
        "q5": {
          "t": "mcq",
          "c": "b"
        },
        "q6": {
          "t": "fib",
          "a": [
            "import",
            "Import"
          ]
        },
        "q7": {
          "t": "po",
          "e": "8"
        },
        "q8": {
          "t": "po",
          "e": "15"
        },
        "q9": {
          "t": "po",
          "e": "8"
        },
        "q10": {
          "t": "po",
          "e": "2.5"
        },
        "q11": {
          "t": "mcq",
          "c": "b"
        },
        "q12": {
          "t": "po",
          "e": "hi\nNone"
        },
        "q13": {
          "t": "mcq",
          "c": "b"
        },
        "q14": {
          "t": "fib",
          "a": [
            "None",
            "none"
          ]
        },
        "q15": {
          "t": "po",
          "e": "False"
        },
        "q16": {
          "t": "po",
          "e": "True"
        },
        "q17": {
          "t": "po",
          "e": "False"
        },
        "q18": {
          "t": "mcq",
          "c": "a"
        },
        "q19": {
          "t": "po",
          "e": "0\n1\n1\n2"
        },
        "q20": {
          "t": "mcq",
          "c": "b"
        },
        "q21": {
          "t": "fib",
          "a": [
            "pass",
            "Pass"
          ]
        },
        "q22": {
          "t": "po",
          "e": "done"
        },
        "q23": {
          "t": "po",
          "e": "6"
        },
        "q24": {
          "t": "po",
          "e": "0-1-2-"
        },
        "q25": {
          "t": "mcq",
          "c": "b"
        }
      }
    ]
  },
  "completing-basics.progress-test-1.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "6.0"
        },
        "q3": {
          "t": "po",
          "e": "4"
        },
        "q4": {
          "t": "po",
          "e": "5"
        },
        "q5": {
          "t": "mcq",
          "c": "b"
        },
        "q6": {
          "t": "fib",
          "a": [
            "import",
            "Import"
          ]
        },
        "q7": {
          "t": "po",
          "e": "8"
        },
        "q8": {
          "t": "po",
          "e": "15"
        },
        "q9": {
          "t": "po",
          "e": "8"
        },
        "q10": {
          "t": "po",
          "e": "2.5"
        },
        "q11": {
          "t": "mcq",
          "c": "b"
        },
        "q12": {
          "t": "po",
          "e": "hi\nNone"
        },
        "q13": {
          "t": "mcq",
          "c": "b"
        },
        "q14": {
          "t": "fib",
          "a": [
            "None",
            "none"
          ]
        },
        "q15": {
          "t": "po",
          "e": "False"
        },
        "q16": {
          "t": "po",
          "e": "True"
        },
        "q17": {
          "t": "po",
          "e": "False"
        },
        "q18": {
          "t": "mcq",
          "c": "a"
        },
        "q19": {
          "t": "po",
          "e": "0\n1\n1\n2"
        },
        "q20": {
          "t": "mcq",
          "c": "b"
        },
        "q21": {
          "t": "fib",
          "a": [
            "pass",
            "Pass"
          ]
        },
        "q22": {
          "t": "po",
          "e": "done"
        },
        "q23": {
          "t": "po",
          "e": "6"
        },
        "q24": {
          "t": "po",
          "e": "0-1-2-"
        },
        "q25": {
          "t": "mcq",
          "c": "b"
        }
      }
    ]
  },
  "data-types.final-test.test": {
    "drawCount": 15,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "a"
        },
        "q2": {
          "t": "po",
          "e": "a"
        },
        "q3": {
          "t": "po",
          "e": "[1, 2, 3, 4]"
        },
        "q4": {
          "t": "mcq",
          "c": "b"
        },
        "q5": {
          "t": "po",
          "e": "3"
        },
        "q6": {
          "t": "fib",
          "a": [
            "append",
            "append()"
          ]
        },
        "q7": {
          "t": "po",
          "e": "z"
        },
        "q8": {
          "t": "po",
          "e": "[9, 2, 3]"
        },
        "q9": {
          "t": "mcq",
          "c": "b"
        },
        "q10": {
          "t": "po",
          "e": "6"
        },
        "q11": {
          "t": "mcq",
          "c": "b"
        },
        "q12": {
          "t": "po",
          "e": "1"
        },
        "q13": {
          "t": "fib",
          "a": [
            "0",
            "zero",
            "Zero"
          ]
        },
        "q14": {
          "t": "po",
          "e": "[4, 6]"
        },
        "q15": {
          "t": "po",
          "e": "4"
        },
        "q16": {
          "t": "mcq",
          "c": "b"
        },
        "q17": {
          "t": "po",
          "e": "3"
        },
        "q18": {
          "t": "po",
          "e": "1\n2\n3"
        },
        "q19": {
          "t": "mcq",
          "c": "a"
        },
        "q20": {
          "t": "po",
          "e": "30"
        },
        "q21": {
          "t": "fib",
          "a": [
            "immutable",
            "Immutable"
          ]
        },
        "q22": {
          "t": "po",
          "e": "1"
        },
        "q23": {
          "t": "po",
          "e": "c"
        },
        "q24": {
          "t": "mcq",
          "c": "b"
        },
        "q25": {
          "t": "po",
          "e": "[1, 2, 3, 4]"
        }
      },
      {
        "q1": {
          "t": "po",
          "e": "h"
        },
        "q2": {
          "t": "po",
          "e": "a"
        },
        "q3": {
          "t": "po",
          "e": "Pyt"
        },
        "q4": {
          "t": "po",
          "e": "5"
        },
        "q5": {
          "t": "po",
          "e": "ABC"
        },
        "q6": {
          "t": "po",
          "e": "abc"
        },
        "q7": {
          "t": "mcq",
          "c": "b"
        },
        "q8": {
          "t": "fib",
          "a": [
            "split",
            "split()"
          ]
        },
        "q9": {
          "t": "po",
          "e": "['a', 'b', 'c']"
        },
        "q10": {
          "t": "po",
          "e": "heLLo"
        },
        "q11": {
          "t": "po",
          "e": "n"
        },
        "q12": {
          "t": "po",
          "e": "h\ni"
        },
        "q13": {
          "t": "mcq",
          "c": "c"
        },
        "q14": {
          "t": "po",
          "e": "1"
        },
        "q15": {
          "t": "po",
          "e": "9"
        },
        "q16": {
          "t": "po",
          "e": "2"
        },
        "q17": {
          "t": "po",
          "e": "True"
        },
        "q18": {
          "t": "po",
          "e": "False"
        },
        "q19": {
          "t": "fib",
          "a": [
            "value",
            "Value"
          ]
        },
        "q20": {
          "t": "po",
          "e": "10"
        },
        "q21": {
          "t": "mcq",
          "c": "c"
        },
        "q22": {
          "t": "po",
          "e": "2"
        },
        "q23": {
          "t": "po",
          "e": "prog"
        },
        "q24": {
          "t": "mcq",
          "c": "b"
        },
        "q25": {
          "t": "po",
          "e": "['Hello', 'World']"
        }
      },
      {
        "q1": {
          "t": "po",
          "e": "3"
        },
        "q2": {
          "t": "po",
          "e": "True"
        },
        "q3": {
          "t": "po",
          "e": "4"
        },
        "q4": {
          "t": "po",
          "e": "3"
        },
        "q5": {
          "t": "mcq",
          "c": "b"
        },
        "q6": {
          "t": "fib",
          "a": [
            "set",
            "Set",
            "set()"
          ]
        },
        "q7": {
          "t": "po",
          "e": "a-b-c"
        },
        "q8": {
          "t": "po",
          "e": "['x', 'y', 'z']"
        },
        "q9": {
          "t": "po",
          "e": "[0, 1, 2, 3]"
        },
        "q10": {
          "t": "po",
          "e": "[2, 3, 4, 5]"
        },
        "q11": {
          "t": "po",
          "e": "[0, 2, 4, 6, 8]"
        },
        "q12": {
          "t": "mcq",
          "c": "b"
        },
        "q13": {
          "t": "po",
          "e": "[3, 2, 1]"
        },
        "q14": {
          "t": "po",
          "e": "(1, 2, 3)"
        },
        "q15": {
          "t": "po",
          "e": "[4, 5, 6]"
        },
        "q16": {
          "t": "fib",
          "a": [
            "split",
            "split()"
          ]
        },
        "q17": {
          "t": "po",
          "e": "5!"
        },
        "q18": {
          "t": "po",
          "e": "10"
        },
        "q19": {
          "t": "mcq",
          "c": "c"
        },
        "q20": {
          "t": "po",
          "e": "True"
        },
        "q21": {
          "t": "po",
          "e": "False"
        },
        "q22": {
          "t": "mcq",
          "c": "b"
        },
        "q23": {
          "t": "po",
          "e": "10"
        },
        "q24": {
          "t": "fib",
          "a": [
            "0",
            "zero",
            "Zero"
          ]
        },
        "q25": {
          "t": "po",
          "e": "3"
        }
      }
    ]
  },
  "data-types.progress-test-1.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "a"
        },
        "q2": {
          "t": "po",
          "e": "a"
        },
        "q3": {
          "t": "po",
          "e": "[1, 2, 3, 4]"
        },
        "q4": {
          "t": "mcq",
          "c": "b"
        },
        "q5": {
          "t": "po",
          "e": "3"
        },
        "q6": {
          "t": "fib",
          "a": [
            "append",
            "append()"
          ]
        },
        "q7": {
          "t": "po",
          "e": "z"
        },
        "q8": {
          "t": "po",
          "e": "[9, 2, 3]"
        },
        "q9": {
          "t": "mcq",
          "c": "b"
        },
        "q10": {
          "t": "po",
          "e": "6"
        },
        "q11": {
          "t": "mcq",
          "c": "b"
        },
        "q12": {
          "t": "po",
          "e": "1"
        },
        "q13": {
          "t": "fib",
          "a": [
            "0",
            "zero",
            "Zero"
          ]
        },
        "q14": {
          "t": "po",
          "e": "[4, 6]"
        },
        "q15": {
          "t": "po",
          "e": "4"
        },
        "q16": {
          "t": "mcq",
          "c": "b"
        },
        "q17": {
          "t": "po",
          "e": "3"
        },
        "q18": {
          "t": "po",
          "e": "1\n2\n3"
        },
        "q19": {
          "t": "mcq",
          "c": "a"
        },
        "q20": {
          "t": "po",
          "e": "30"
        },
        "q21": {
          "t": "fib",
          "a": [
            "immutable",
            "Immutable"
          ]
        },
        "q22": {
          "t": "po",
          "e": "1"
        },
        "q23": {
          "t": "po",
          "e": "c"
        },
        "q24": {
          "t": "mcq",
          "c": "b"
        },
        "q25": {
          "t": "po",
          "e": "[1, 2, 3, 4]"
        }
      }
    ]
  },
  "data-types.progress-test-2.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "po",
          "e": "h"
        },
        "q2": {
          "t": "po",
          "e": "a"
        },
        "q3": {
          "t": "po",
          "e": "Pyt"
        },
        "q4": {
          "t": "po",
          "e": "5"
        },
        "q5": {
          "t": "po",
          "e": "ABC"
        },
        "q6": {
          "t": "po",
          "e": "abc"
        },
        "q7": {
          "t": "mcq",
          "c": "b"
        },
        "q8": {
          "t": "fib",
          "a": [
            "split",
            "split()"
          ]
        },
        "q9": {
          "t": "po",
          "e": "['a', 'b', 'c']"
        },
        "q10": {
          "t": "po",
          "e": "heLLo"
        },
        "q11": {
          "t": "po",
          "e": "n"
        },
        "q12": {
          "t": "po",
          "e": "h\ni"
        },
        "q13": {
          "t": "mcq",
          "c": "c"
        },
        "q14": {
          "t": "po",
          "e": "1"
        },
        "q15": {
          "t": "po",
          "e": "9"
        },
        "q16": {
          "t": "po",
          "e": "2"
        },
        "q17": {
          "t": "po",
          "e": "True"
        },
        "q18": {
          "t": "po",
          "e": "False"
        },
        "q19": {
          "t": "fib",
          "a": [
            "value",
            "Value"
          ]
        },
        "q20": {
          "t": "po",
          "e": "10"
        },
        "q21": {
          "t": "mcq",
          "c": "c"
        },
        "q22": {
          "t": "po",
          "e": "2"
        },
        "q23": {
          "t": "po",
          "e": "prog"
        },
        "q24": {
          "t": "mcq",
          "c": "b"
        },
        "q25": {
          "t": "po",
          "e": "['Hello', 'World']"
        }
      }
    ]
  },
  "data-types.progress-test-3.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "po",
          "e": "3"
        },
        "q2": {
          "t": "po",
          "e": "True"
        },
        "q3": {
          "t": "po",
          "e": "4"
        },
        "q4": {
          "t": "po",
          "e": "3"
        },
        "q5": {
          "t": "mcq",
          "c": "b"
        },
        "q6": {
          "t": "fib",
          "a": [
            "set",
            "Set",
            "set()"
          ]
        },
        "q7": {
          "t": "po",
          "e": "a-b-c"
        },
        "q8": {
          "t": "po",
          "e": "['x', 'y', 'z']"
        },
        "q9": {
          "t": "po",
          "e": "[0, 1, 2, 3]"
        },
        "q10": {
          "t": "po",
          "e": "[2, 3, 4, 5]"
        },
        "q11": {
          "t": "po",
          "e": "[0, 2, 4, 6, 8]"
        },
        "q12": {
          "t": "mcq",
          "c": "b"
        },
        "q13": {
          "t": "po",
          "e": "[3, 2, 1]"
        },
        "q14": {
          "t": "po",
          "e": "(1, 2, 3)"
        },
        "q15": {
          "t": "po",
          "e": "[4, 5, 6]"
        },
        "q16": {
          "t": "fib",
          "a": [
            "split",
            "split()"
          ]
        },
        "q17": {
          "t": "po",
          "e": "5!"
        },
        "q18": {
          "t": "po",
          "e": "10"
        },
        "q19": {
          "t": "mcq",
          "c": "c"
        },
        "q20": {
          "t": "po",
          "e": "True"
        },
        "q21": {
          "t": "po",
          "e": "False"
        },
        "q22": {
          "t": "mcq",
          "c": "b"
        },
        "q23": {
          "t": "po",
          "e": "10"
        },
        "q24": {
          "t": "fib",
          "a": [
            "0",
            "zero",
            "Zero"
          ]
        },
        "q25": {
          "t": "po",
          "e": "3"
        }
      }
    ]
  },
  "decision-making-loops.final-test.test": {
    "drawCount": 20,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "True"
        },
        "q3": {
          "t": "mcq",
          "c": "c"
        },
        "q4": {
          "t": "po",
          "e": "True"
        },
        "q5": {
          "t": "po",
          "e": "False"
        },
        "q6": {
          "t": "fib",
          "a": [
            "==",
            "eq"
          ]
        },
        "q7": {
          "t": "mcq",
          "c": "b"
        },
        "q8": {
          "t": "po",
          "e": "False"
        },
        "q9": {
          "t": "po",
          "e": "False"
        },
        "q10": {
          "t": "po",
          "e": "True"
        },
        "q11": {
          "t": "mcq",
          "c": "c"
        },
        "q12": {
          "t": "po",
          "e": "yes"
        },
        "q13": {
          "t": "po",
          "e": "minor"
        },
        "q14": {
          "t": "mcq",
          "c": "b"
        },
        "q15": {
          "t": "po",
          "e": "zero"
        },
        "q16": {
          "t": "fib",
          "a": [
            "elif",
            "Elif"
          ]
        },
        "q17": {
          "t": "po",
          "e": "hot"
        },
        "q18": {
          "t": "mcq",
          "c": "b"
        },
        "q19": {
          "t": "po",
          "e": "False"
        },
        "q20": {
          "t": "po",
          "e": "True"
        },
        "q21": {
          "t": "fib",
          "a": [
            "4",
            "four",
            "Four"
          ]
        },
        "q22": {
          "t": "po",
          "e": "between"
        },
        "q23": {
          "t": "mcq",
          "c": "b"
        },
        "q24": {
          "t": "po",
          "e": "B"
        },
        "q25": {
          "t": "po",
          "e": "True"
        },
        "q26": {
          "t": "po",
          "e": "Even"
        },
        "q27": {
          "t": "po",
          "e": "Can vote"
        },
        "q28": {
          "t": "mcq",
          "c": "b"
        },
        "q29": {
          "t": "po",
          "e": "3"
        },
        "q30": {
          "t": "po",
          "e": "Negative"
        }
      },
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "False"
        },
        "q3": {
          "t": "po",
          "e": "True"
        },
        "q4": {
          "t": "po",
          "e": "False"
        },
        "q5": {
          "t": "mcq",
          "c": "c"
        },
        "q6": {
          "t": "fib",
          "a": [
            "not",
            "Not"
          ]
        },
        "q7": {
          "t": "po",
          "e": "True"
        },
        "q8": {
          "t": "po",
          "e": "False"
        },
        "q9": {
          "t": "mcq",
          "c": "a"
        },
        "q10": {
          "t": "po",
          "e": "True"
        },
        "q11": {
          "t": "mcq",
          "c": "b"
        },
        "q12": {
          "t": "po",
          "e": "1\n2\n3"
        },
        "q13": {
          "t": "mcq",
          "c": "b"
        },
        "q14": {
          "t": "po",
          "e": "3\n2\n1"
        },
        "q15": {
          "t": "mcq",
          "c": "c"
        },
        "q16": {
          "t": "fib",
          "a": [
            "iteration",
            "Iteration"
          ]
        },
        "q17": {
          "t": "po",
          "e": "10"
        },
        "q18": {
          "t": "po",
          "e": "done"
        },
        "q19": {
          "t": "mcq",
          "c": "b"
        },
        "q20": {
          "t": "po",
          "e": "loop\nloop\nloop"
        },
        "q21": {
          "t": "fib",
          "a": [
            "while",
            "While"
          ]
        },
        "q22": {
          "t": "po",
          "e": "True"
        },
        "q23": {
          "t": "mcq",
          "c": "b"
        },
        "q24": {
          "t": "po",
          "e": "2\n4\n6\n8"
        },
        "q25": {
          "t": "mcq",
          "c": "b"
        },
        "q26": {
          "t": "po",
          "e": "True"
        },
        "q27": {
          "t": "po",
          "e": "10"
        },
        "q28": {
          "t": "po",
          "e": "3"
        },
        "q29": {
          "t": "mcq",
          "c": "b"
        },
        "q30": {
          "t": "po",
          "e": "True"
        }
      },
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "0\n1\n2"
        },
        "q3": {
          "t": "po",
          "e": "2\n3\n4"
        },
        "q4": {
          "t": "mcq",
          "c": "c"
        },
        "q5": {
          "t": "po",
          "e": "0\n2\n4\n6\n8"
        },
        "q6": {
          "t": "fib",
          "a": [
            "0",
            "zero",
            "Zero"
          ]
        },
        "q7": {
          "t": "po",
          "e": "a\nb"
        },
        "q8": {
          "t": "po",
          "e": "6"
        },
        "q9": {
          "t": "mcq",
          "c": "a"
        },
        "q10": {
          "t": "po",
          "e": "1\n2"
        },
        "q11": {
          "t": "po",
          "e": "1\n3\n4"
        },
        "q12": {
          "t": "mcq",
          "c": "b"
        },
        "q13": {
          "t": "mcq",
          "c": "b"
        },
        "q14": {
          "t": "fib",
          "a": [
            "break",
            "Break"
          ]
        },
        "q15": {
          "t": "fib",
          "a": [
            "continue",
            "Continue"
          ]
        },
        "q16": {
          "t": "po",
          "e": "3\n2\n1"
        },
        "q17": {
          "t": "po",
          "e": "1\n4\n7"
        },
        "q18": {
          "t": "mcq",
          "c": "b"
        },
        "q19": {
          "t": "po",
          "e": "1\n4\n9"
        },
        "q20": {
          "t": "mcq",
          "c": "b"
        },
        "q21": {
          "t": "po",
          "e": "3"
        },
        "q22": {
          "t": "po",
          "e": "1\n3\n5"
        },
        "q23": {
          "t": "po",
          "e": "15"
        },
        "q24": {
          "t": "mcq",
          "c": "c"
        },
        "q25": {
          "t": "fib",
          "a": [
            "step",
            "Step"
          ]
        },
        "q26": {
          "t": "po",
          "e": "1\n3\n5"
        },
        "q27": {
          "t": "po",
          "e": "15"
        },
        "q28": {
          "t": "po",
          "e": "24"
        },
        "q29": {
          "t": "po",
          "e": "1\n2\n4\n5"
        },
        "q30": {
          "t": "mcq",
          "c": "b"
        }
      }
    ]
  },
  "decision-making-loops.progress-test-1.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "True"
        },
        "q3": {
          "t": "mcq",
          "c": "c"
        },
        "q4": {
          "t": "po",
          "e": "True"
        },
        "q5": {
          "t": "po",
          "e": "False"
        },
        "q6": {
          "t": "fib",
          "a": [
            "==",
            "eq"
          ]
        },
        "q7": {
          "t": "mcq",
          "c": "b"
        },
        "q8": {
          "t": "po",
          "e": "False"
        },
        "q9": {
          "t": "po",
          "e": "False"
        },
        "q10": {
          "t": "po",
          "e": "True"
        },
        "q11": {
          "t": "mcq",
          "c": "c"
        },
        "q12": {
          "t": "po",
          "e": "yes"
        },
        "q13": {
          "t": "po",
          "e": "minor"
        },
        "q14": {
          "t": "mcq",
          "c": "b"
        },
        "q15": {
          "t": "po",
          "e": "zero"
        },
        "q16": {
          "t": "fib",
          "a": [
            "elif",
            "Elif"
          ]
        },
        "q17": {
          "t": "po",
          "e": "hot"
        },
        "q18": {
          "t": "mcq",
          "c": "b"
        },
        "q19": {
          "t": "po",
          "e": "False"
        },
        "q20": {
          "t": "po",
          "e": "True"
        },
        "q21": {
          "t": "fib",
          "a": [
            "4",
            "four",
            "Four"
          ]
        },
        "q22": {
          "t": "po",
          "e": "between"
        },
        "q23": {
          "t": "mcq",
          "c": "b"
        },
        "q24": {
          "t": "po",
          "e": "B"
        },
        "q25": {
          "t": "po",
          "e": "True"
        },
        "q26": {
          "t": "po",
          "e": "Even"
        },
        "q27": {
          "t": "po",
          "e": "Can vote"
        },
        "q28": {
          "t": "mcq",
          "c": "b"
        },
        "q29": {
          "t": "po",
          "e": "3"
        },
        "q30": {
          "t": "po",
          "e": "Negative"
        }
      }
    ]
  },
  "decision-making-loops.progress-test-2.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "False"
        },
        "q3": {
          "t": "po",
          "e": "True"
        },
        "q4": {
          "t": "po",
          "e": "False"
        },
        "q5": {
          "t": "mcq",
          "c": "c"
        },
        "q6": {
          "t": "fib",
          "a": [
            "not",
            "Not"
          ]
        },
        "q7": {
          "t": "po",
          "e": "True"
        },
        "q8": {
          "t": "po",
          "e": "False"
        },
        "q9": {
          "t": "mcq",
          "c": "a"
        },
        "q10": {
          "t": "po",
          "e": "True"
        },
        "q11": {
          "t": "mcq",
          "c": "b"
        },
        "q12": {
          "t": "po",
          "e": "1\n2\n3"
        },
        "q13": {
          "t": "mcq",
          "c": "b"
        },
        "q14": {
          "t": "po",
          "e": "3\n2\n1"
        },
        "q15": {
          "t": "mcq",
          "c": "c"
        },
        "q16": {
          "t": "fib",
          "a": [
            "iteration",
            "Iteration"
          ]
        },
        "q17": {
          "t": "po",
          "e": "10"
        },
        "q18": {
          "t": "po",
          "e": "done"
        },
        "q19": {
          "t": "mcq",
          "c": "b"
        },
        "q20": {
          "t": "po",
          "e": "loop\nloop\nloop"
        },
        "q21": {
          "t": "fib",
          "a": [
            "while",
            "While"
          ]
        },
        "q22": {
          "t": "po",
          "e": "True"
        },
        "q23": {
          "t": "mcq",
          "c": "b"
        },
        "q24": {
          "t": "po",
          "e": "2\n4\n6\n8"
        },
        "q25": {
          "t": "mcq",
          "c": "b"
        },
        "q26": {
          "t": "po",
          "e": "True"
        },
        "q27": {
          "t": "po",
          "e": "10"
        },
        "q28": {
          "t": "po",
          "e": "3"
        },
        "q29": {
          "t": "mcq",
          "c": "b"
        },
        "q30": {
          "t": "po",
          "e": "True"
        }
      }
    ]
  },
  "decision-making-loops.progress-test-3.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "0\n1\n2"
        },
        "q3": {
          "t": "po",
          "e": "2\n3\n4"
        },
        "q4": {
          "t": "mcq",
          "c": "c"
        },
        "q5": {
          "t": "po",
          "e": "0\n2\n4\n6\n8"
        },
        "q6": {
          "t": "fib",
          "a": [
            "0",
            "zero",
            "Zero"
          ]
        },
        "q7": {
          "t": "po",
          "e": "a\nb"
        },
        "q8": {
          "t": "po",
          "e": "6"
        },
        "q9": {
          "t": "mcq",
          "c": "a"
        },
        "q10": {
          "t": "po",
          "e": "1\n2"
        },
        "q11": {
          "t": "po",
          "e": "1\n3\n4"
        },
        "q12": {
          "t": "mcq",
          "c": "b"
        },
        "q13": {
          "t": "mcq",
          "c": "b"
        },
        "q14": {
          "t": "fib",
          "a": [
            "break",
            "Break"
          ]
        },
        "q15": {
          "t": "fib",
          "a": [
            "continue",
            "Continue"
          ]
        },
        "q16": {
          "t": "po",
          "e": "3\n2\n1"
        },
        "q17": {
          "t": "po",
          "e": "1\n4\n7"
        },
        "q18": {
          "t": "mcq",
          "c": "b"
        },
        "q19": {
          "t": "po",
          "e": "1\n4\n9"
        },
        "q20": {
          "t": "mcq",
          "c": "b"
        },
        "q21": {
          "t": "po",
          "e": "3"
        },
        "q22": {
          "t": "po",
          "e": "1\n3\n5"
        },
        "q23": {
          "t": "po",
          "e": "15"
        },
        "q24": {
          "t": "mcq",
          "c": "c"
        },
        "q25": {
          "t": "fib",
          "a": [
            "step",
            "Step"
          ]
        },
        "q26": {
          "t": "po",
          "e": "1\n3\n5"
        },
        "q27": {
          "t": "po",
          "e": "15"
        },
        "q28": {
          "t": "po",
          "e": "24"
        },
        "q29": {
          "t": "po",
          "e": "1\n2\n4\n5"
        },
        "q30": {
          "t": "mcq",
          "c": "b"
        }
      }
    ]
  },
  "functions.final-test.test": {
    "drawCount": 15,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "Hi"
        },
        "q3": {
          "t": "po",
          "e": "5"
        },
        "q4": {
          "t": "mcq",
          "c": "b"
        },
        "q5": {
          "t": "po",
          "e": "10"
        },
        "q6": {
          "t": "fib",
          "a": [
            "return",
            "Return"
          ]
        },
        "q7": {
          "t": "po",
          "e": "Hello Sam"
        },
        "q8": {
          "t": "mcq",
          "c": "b"
        },
        "q9": {
          "t": "po",
          "e": "9"
        },
        "q10": {
          "t": "po",
          "e": "a\nb"
        },
        "q11": {
          "t": "mcq",
          "c": "b"
        },
        "q12": {
          "t": "po",
          "e": "9\n5"
        },
        "q13": {
          "t": "fib",
          "a": [
            "local",
            "Local"
          ]
        },
        "q14": {
          "t": "po",
          "e": "10"
        },
        "q15": {
          "t": "po",
          "e": "Hi"
        },
        "q16": {
          "t": "mcq",
          "c": "c"
        },
        "q17": {
          "t": "po",
          "e": "12"
        },
        "q18": {
          "t": "fib",
          "a": [
            "parameters",
            "parameter",
            "Parameters"
          ]
        },
        "q19": {
          "t": "po",
          "e": "Hey"
        },
        "q20": {
          "t": "mcq",
          "c": "a"
        },
        "q21": {
          "t": "po",
          "e": "6"
        },
        "q22": {
          "t": "po",
          "e": "11"
        },
        "q23": {
          "t": "mcq",
          "c": "b"
        },
        "q24": {
          "t": "po",
          "e": "15"
        },
        "q25": {
          "t": "fib",
          "a": [
            "()",
            "run()",
            "parentheses",
            "brackets"
          ]
        }
      }
    ]
  },
  "functions.progress-test-1.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "Hi"
        },
        "q3": {
          "t": "po",
          "e": "5"
        },
        "q4": {
          "t": "mcq",
          "c": "b"
        },
        "q5": {
          "t": "po",
          "e": "10"
        },
        "q6": {
          "t": "fib",
          "a": [
            "return",
            "Return"
          ]
        },
        "q7": {
          "t": "po",
          "e": "Hello Sam"
        },
        "q8": {
          "t": "mcq",
          "c": "b"
        },
        "q9": {
          "t": "po",
          "e": "9"
        },
        "q10": {
          "t": "po",
          "e": "a\nb"
        },
        "q11": {
          "t": "mcq",
          "c": "b"
        },
        "q12": {
          "t": "po",
          "e": "9\n5"
        },
        "q13": {
          "t": "fib",
          "a": [
            "local",
            "Local"
          ]
        },
        "q14": {
          "t": "po",
          "e": "10"
        },
        "q15": {
          "t": "po",
          "e": "Hi"
        },
        "q16": {
          "t": "mcq",
          "c": "c"
        },
        "q17": {
          "t": "po",
          "e": "12"
        },
        "q18": {
          "t": "fib",
          "a": [
            "parameters",
            "parameter",
            "Parameters"
          ]
        },
        "q19": {
          "t": "po",
          "e": "Hey"
        },
        "q20": {
          "t": "mcq",
          "c": "a"
        },
        "q21": {
          "t": "po",
          "e": "6"
        },
        "q22": {
          "t": "po",
          "e": "11"
        },
        "q23": {
          "t": "mcq",
          "c": "b"
        },
        "q24": {
          "t": "po",
          "e": "15"
        },
        "q25": {
          "t": "fib",
          "a": [
            "()",
            "run()",
            "parentheses",
            "brackets"
          ]
        }
      }
    ]
  },
  "introduction.final-test.test": {
    "drawCount": 20,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "Hello, World!"
        },
        "q3": {
          "t": "mcq",
          "c": "b"
        },
        "q4": {
          "t": "fib",
          "a": [
            "string",
            "String"
          ]
        },
        "q5": {
          "t": "po",
          "e": "5\n343.44"
        },
        "q6": {
          "t": "mcq",
          "c": "c"
        },
        "q7": {
          "t": "mcq",
          "c": "c"
        },
        "q8": {
          "t": "po",
          "e": "Python\n75"
        },
        "q9": {
          "t": "fib",
          "a": [
            "integers",
            "integer",
            "Integer",
            "Integers",
            "int",
            "ints"
          ]
        },
        "q10": {
          "t": "mcq",
          "c": "c"
        },
        "q11": {
          "t": "mcq",
          "c": "b"
        },
        "q12": {
          "t": "po",
          "e": "Python is fun"
        },
        "q13": {
          "t": "fib",
          "a": [
            "quotation",
            "quote",
            "quotation mark",
            "quotation marks",
            "quote marks",
            "quotes"
          ]
        },
        "q14": {
          "t": "po",
          "e": "42\n7.5"
        },
        "q15": {
          "t": "mcq",
          "c": "c"
        },
        "q16": {
          "t": "po",
          "e": "Coding"
        },
        "q17": {
          "t": "fib",
          "a": [
            "single",
            "Single"
          ]
        },
        "q18": {
          "t": "po",
          "e": "100\nWelcome\n3.5"
        },
        "q19": {
          "t": "mcq",
          "c": "b"
        },
        "q20": {
          "t": "po",
          "e": "0\n-8"
        },
        "q21": {
          "t": "mcq",
          "c": "b"
        },
        "q22": {
          "t": "fib",
          "a": [
            "floating-point",
            "floating point",
            "float",
            "floats",
            "floating-point number",
            "floating point number"
          ]
        },
        "q23": {
          "t": "po",
          "e": "Hello\nWorld"
        },
        "q24": {
          "t": "mcq",
          "c": "b"
        },
        "q25": {
          "t": "fib",
          "a": [
            "line",
            "Line"
          ]
        }
      },
      {
        "q1": {
          "t": "mcq",
          "c": "c"
        },
        "q2": {
          "t": "po",
          "e": "5"
        },
        "q3": {
          "t": "mcq",
          "c": "b"
        },
        "q4": {
          "t": "po",
          "e": "Hello"
        },
        "q5": {
          "t": "po",
          "e": "greeting"
        },
        "q6": {
          "t": "po",
          "e": "25.5"
        },
        "q7": {
          "t": "fib",
          "a": [
            "=",
            "equals"
          ]
        },
        "q8": {
          "t": "mcq",
          "c": "c"
        },
        "q9": {
          "t": "po",
          "e": "pink"
        },
        "q10": {
          "t": "mcq",
          "c": "d"
        },
        "q11": {
          "t": "po",
          "e": "7"
        },
        "q12": {
          "t": "mcq",
          "c": "b"
        },
        "q13": {
          "t": "fib",
          "a": [
            "commenting",
            "comment"
          ]
        },
        "q14": {
          "t": "po",
          "e": "third"
        },
        "q15": {
          "t": "mcq",
          "c": "c"
        },
        "q16": {
          "t": "po",
          "e": "19\n42"
        },
        "q17": {
          "t": "fib",
          "a": [
            "value"
          ]
        },
        "q18": {
          "t": "po",
          "e": "8"
        },
        "q19": {
          "t": "mcq",
          "c": "a"
        },
        "q20": {
          "t": "fib",
          "a": [
            "underscores",
            "underscore",
            "underscores (_)",
            "an underscore",
            "_"
          ]
        },
        "q21": {
          "t": "po",
          "e": "3"
        },
        "q22": {
          "t": "mcq",
          "c": "d"
        },
        "q23": {
          "t": "mcq",
          "c": "b"
        },
        "q24": {
          "t": "po",
          "e": "10"
        },
        "q25": {
          "t": "fib",
          "a": [
            "sensitive",
            "case-sensitive"
          ]
        }
      },
      {
        "q1": {
          "t": "po",
          "e": "Hello, Alex"
        },
        "q2": {
          "t": "fib",
          "a": [
            "\\n"
          ]
        },
        "q3": {
          "t": "po",
          "e": "London\nis beautiful"
        },
        "q4": {
          "t": "po",
          "e": "Sara is 22 years old."
        },
        "q5": {
          "t": "po",
          "e": "2.5"
        },
        "q6": {
          "t": "po",
          "e": "3"
        },
        "q7": {
          "t": "po",
          "e": "1"
        },
        "q8": {
          "t": "po",
          "e": "8"
        },
        "q9": {
          "t": "mcq",
          "c": "c"
        },
        "q10": {
          "t": "mcq",
          "c": "b"
        },
        "q11": {
          "t": "mcq",
          "c": "c"
        },
        "q12": {
          "t": "po",
          "e": "Score: 90 points"
        },
        "q13": {
          "t": "fib",
          "a": [
            "quotient",
            "Quotient"
          ]
        },
        "q14": {
          "t": "mcq",
          "c": "b"
        },
        "q15": {
          "t": "po",
          "e": "Line one\nLine two\nLine three"
        },
        "q16": {
          "t": "po",
          "e": "Ada Lovelace"
        },
        "q17": {
          "t": "po",
          "e": "Total: 12"
        },
        "q18": {
          "t": "po",
          "e": "5.0"
        },
        "q19": {
          "t": "mcq",
          "c": "b"
        },
        "q20": {
          "t": "po",
          "e": "4.0"
        },
        "q21": {
          "t": "fib",
          "a": [
            "float",
            "Float",
            "floating-point",
            "floating point"
          ]
        },
        "q22": {
          "t": "fib",
          "a": [
            "precedence",
            "Precedence"
          ]
        },
        "q23": {
          "t": "fib",
          "a": [
            "15"
          ]
        },
        "q24": {
          "t": "mcq",
          "c": "b"
        },
        "q25": {
          "t": "mcq",
          "c": "b"
        }
      },
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "30"
        },
        "q3": {
          "t": "mcq",
          "c": "d"
        },
        "q4": {
          "t": "po",
          "e": "10.0"
        },
        "q5": {
          "t": "po",
          "e": "7.0"
        },
        "q6": {
          "t": "fib",
          "a": [
            "input",
            "input()",
            "Input",
            "INPUT"
          ]
        },
        "q7": {
          "t": "mcq",
          "c": "c"
        },
        "q8": {
          "t": "mcq",
          "c": "b"
        },
        "q9": {
          "t": "po",
          "e": "21"
        },
        "q10": {
          "t": "fib",
          "a": [
            "str(n)",
            "str( n )",
            "str (n)"
          ]
        },
        "q11": {
          "t": "mcq",
          "c": "c"
        },
        "q12": {
          "t": "po",
          "e": "38"
        },
        "q13": {
          "t": "fib",
          "a": [
            "conversion",
            "Conversion"
          ]
        },
        "q14": {
          "t": "mcq",
          "c": "b"
        },
        "q15": {
          "t": "po",
          "e": "11"
        },
        "q16": {
          "t": "mcq",
          "c": "c"
        },
        "q17": {
          "t": "fib",
          "a": [
            "ValueError",
            "value error",
            "valueerror"
          ]
        },
        "q18": {
          "t": "mcq",
          "c": "b"
        },
        "q19": {
          "t": "po",
          "e": "14.5"
        },
        "q20": {
          "t": "fib",
          "a": [
            "string",
            "String",
            "str"
          ]
        },
        "q21": {
          "t": "po",
          "e": "Age: 30"
        },
        "q22": {
          "t": "mcq",
          "c": "b"
        },
        "q23": {
          "t": "fib",
          "a": [
            "int",
            "int()"
          ]
        },
        "q24": {
          "t": "po",
          "e": "88"
        },
        "q25": {
          "t": "po",
          "e": "3.5"
        }
      }
    ]
  },
  "introduction.progress-test-1.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "Hello, World!"
        },
        "q3": {
          "t": "mcq",
          "c": "b"
        },
        "q4": {
          "t": "fib",
          "a": [
            "string",
            "String"
          ]
        },
        "q5": {
          "t": "po",
          "e": "5\n343.44"
        },
        "q6": {
          "t": "mcq",
          "c": "c"
        },
        "q7": {
          "t": "mcq",
          "c": "c"
        },
        "q8": {
          "t": "po",
          "e": "Python\n75"
        },
        "q9": {
          "t": "fib",
          "a": [
            "integers",
            "integer",
            "Integer",
            "Integers",
            "int",
            "ints"
          ]
        },
        "q10": {
          "t": "mcq",
          "c": "c"
        },
        "q11": {
          "t": "mcq",
          "c": "b"
        },
        "q12": {
          "t": "po",
          "e": "Python is fun"
        },
        "q13": {
          "t": "fib",
          "a": [
            "quotation",
            "quote",
            "quotation mark",
            "quotation marks",
            "quote marks",
            "quotes"
          ]
        },
        "q14": {
          "t": "po",
          "e": "42\n7.5"
        },
        "q15": {
          "t": "mcq",
          "c": "c"
        },
        "q16": {
          "t": "po",
          "e": "Coding"
        },
        "q17": {
          "t": "fib",
          "a": [
            "single",
            "Single"
          ]
        },
        "q18": {
          "t": "po",
          "e": "100\nWelcome\n3.5"
        },
        "q19": {
          "t": "mcq",
          "c": "b"
        },
        "q20": {
          "t": "po",
          "e": "0\n-8"
        },
        "q21": {
          "t": "mcq",
          "c": "b"
        },
        "q22": {
          "t": "fib",
          "a": [
            "floating-point",
            "floating point",
            "float",
            "floats",
            "floating-point number",
            "floating point number"
          ]
        },
        "q23": {
          "t": "po",
          "e": "Hello\nWorld"
        },
        "q24": {
          "t": "mcq",
          "c": "b"
        },
        "q25": {
          "t": "fib",
          "a": [
            "line",
            "Line"
          ]
        }
      }
    ]
  },
  "introduction.progress-test-2.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "c"
        },
        "q2": {
          "t": "po",
          "e": "5"
        },
        "q3": {
          "t": "mcq",
          "c": "b"
        },
        "q4": {
          "t": "po",
          "e": "Hello"
        },
        "q5": {
          "t": "po",
          "e": "greeting"
        },
        "q6": {
          "t": "po",
          "e": "25.5"
        },
        "q7": {
          "t": "fib",
          "a": [
            "=",
            "equals"
          ]
        },
        "q8": {
          "t": "mcq",
          "c": "c"
        },
        "q9": {
          "t": "po",
          "e": "pink"
        },
        "q10": {
          "t": "mcq",
          "c": "d"
        },
        "q11": {
          "t": "po",
          "e": "7"
        },
        "q12": {
          "t": "mcq",
          "c": "b"
        },
        "q13": {
          "t": "fib",
          "a": [
            "commenting",
            "comment"
          ]
        },
        "q14": {
          "t": "po",
          "e": "third"
        },
        "q15": {
          "t": "mcq",
          "c": "c"
        },
        "q16": {
          "t": "po",
          "e": "19\n42"
        },
        "q17": {
          "t": "fib",
          "a": [
            "value"
          ]
        },
        "q18": {
          "t": "po",
          "e": "8"
        },
        "q19": {
          "t": "mcq",
          "c": "a"
        },
        "q20": {
          "t": "fib",
          "a": [
            "underscores",
            "underscore",
            "underscores (_)",
            "an underscore",
            "_"
          ]
        },
        "q21": {
          "t": "po",
          "e": "3"
        },
        "q22": {
          "t": "mcq",
          "c": "d"
        },
        "q23": {
          "t": "mcq",
          "c": "b"
        },
        "q24": {
          "t": "po",
          "e": "10"
        },
        "q25": {
          "t": "fib",
          "a": [
            "sensitive",
            "case-sensitive"
          ]
        }
      }
    ]
  },
  "introduction.progress-test-3.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "po",
          "e": "Hello, Alex"
        },
        "q2": {
          "t": "fib",
          "a": [
            "\\n"
          ]
        },
        "q3": {
          "t": "po",
          "e": "London\nis beautiful"
        },
        "q4": {
          "t": "po",
          "e": "Sara is 22 years old."
        },
        "q5": {
          "t": "po",
          "e": "2.5"
        },
        "q6": {
          "t": "po",
          "e": "3"
        },
        "q7": {
          "t": "po",
          "e": "1"
        },
        "q8": {
          "t": "po",
          "e": "8"
        },
        "q9": {
          "t": "mcq",
          "c": "c"
        },
        "q10": {
          "t": "mcq",
          "c": "b"
        },
        "q11": {
          "t": "mcq",
          "c": "c"
        },
        "q12": {
          "t": "po",
          "e": "Score: 90 points"
        },
        "q13": {
          "t": "fib",
          "a": [
            "quotient",
            "Quotient"
          ]
        },
        "q14": {
          "t": "mcq",
          "c": "b"
        },
        "q15": {
          "t": "po",
          "e": "Line one\nLine two\nLine three"
        },
        "q16": {
          "t": "po",
          "e": "Ada Lovelace"
        },
        "q17": {
          "t": "po",
          "e": "Total: 12"
        },
        "q18": {
          "t": "po",
          "e": "5.0"
        },
        "q19": {
          "t": "mcq",
          "c": "b"
        },
        "q20": {
          "t": "po",
          "e": "4.0"
        },
        "q21": {
          "t": "fib",
          "a": [
            "float",
            "Float",
            "floating-point",
            "floating point"
          ]
        },
        "q22": {
          "t": "fib",
          "a": [
            "precedence",
            "Precedence"
          ]
        },
        "q23": {
          "t": "fib",
          "a": [
            "15"
          ]
        },
        "q24": {
          "t": "mcq",
          "c": "b"
        },
        "q25": {
          "t": "mcq",
          "c": "b"
        }
      }
    ]
  },
  "introduction.progress-test-4.test": {
    "drawCount": 10,
    "banks": [
      {
        "q1": {
          "t": "mcq",
          "c": "b"
        },
        "q2": {
          "t": "po",
          "e": "30"
        },
        "q3": {
          "t": "mcq",
          "c": "d"
        },
        "q4": {
          "t": "po",
          "e": "10.0"
        },
        "q5": {
          "t": "po",
          "e": "7.0"
        },
        "q6": {
          "t": "fib",
          "a": [
            "input",
            "input()",
            "Input",
            "INPUT"
          ]
        },
        "q7": {
          "t": "mcq",
          "c": "c"
        },
        "q8": {
          "t": "mcq",
          "c": "b"
        },
        "q9": {
          "t": "po",
          "e": "21"
        },
        "q10": {
          "t": "fib",
          "a": [
            "str(n)",
            "str( n )",
            "str (n)"
          ]
        },
        "q11": {
          "t": "mcq",
          "c": "c"
        },
        "q12": {
          "t": "po",
          "e": "38"
        },
        "q13": {
          "t": "fib",
          "a": [
            "conversion",
            "Conversion"
          ]
        },
        "q14": {
          "t": "mcq",
          "c": "b"
        },
        "q15": {
          "t": "po",
          "e": "11"
        },
        "q16": {
          "t": "mcq",
          "c": "c"
        },
        "q17": {
          "t": "fib",
          "a": [
            "ValueError",
            "value error",
            "valueerror"
          ]
        },
        "q18": {
          "t": "mcq",
          "c": "b"
        },
        "q19": {
          "t": "po",
          "e": "14.5"
        },
        "q20": {
          "t": "fib",
          "a": [
            "string",
            "String",
            "str"
          ]
        },
        "q21": {
          "t": "po",
          "e": "Age: 30"
        },
        "q22": {
          "t": "mcq",
          "c": "b"
        },
        "q23": {
          "t": "fib",
          "a": [
            "int",
            "int()"
          ]
        },
        "q24": {
          "t": "po",
          "e": "88"
        },
        "q25": {
          "t": "po",
          "e": "3.5"
        }
      }
    ]
  }
}
